-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 17:20:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ehulock
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ehulock` ;

-- -----------------------------------------------------
-- Schema ehulock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ehulock` DEFAULT CHARACTER SET utf8 ;
USE `ehulock` ;

-- -----------------------------------------------------
-- Table `ehulock`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ehulock`.`user` ;

CREATE TABLE IF NOT EXISTS `ehulock`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ehulock`.`kutxatila`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ehulock`.`kutxatila` ;

CREATE TABLE IF NOT EXISTS `ehulock`.`kutxatila` (
  `idKutxatila` INT NOT NULL AUTO_INCREMENT,
  `kodea` VARCHAR(45) NOT NULL,
  `egoera` TINYINT(3) NOT NULL,
  `kokapena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKutxatila`),
  UNIQUE INDEX `kodea_UNIQUE` (`kodea` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ehulock`.`erreserba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ehulock`.`erreserba` ;

CREATE TABLE IF NOT EXISTS `ehulock`.`erreserba` (
  `idErreserba` INT NOT NULL AUTO_INCREMENT,
  `egoera` TINYINT(3) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `abisua` TIMESTAMP NULL,
  `fill_time` TIMESTAMP NULL,
  `empty_time` TIMESTAMP NULL,
  `idUser` INT NOT NULL,
  `idKutxatila` INT NOT NULL,
  PRIMARY KEY (`idErreserba`),
  INDEX `fk_erreserba_kutxatila1_idx` (`idKutxatila` ASC) VISIBLE,
  INDEX `fk_erreserba_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_erreserba_kutxatila1`
    FOREIGN KEY (`idKutxatila`)
    REFERENCES `ehulock`.`kutxatila` (`idKutxatila`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erreserba_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `ehulock`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
